name: Deploy to Heroku Hosting (Production)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.1
      
      - name: Install NPM packages
        run: npm ci
        working-directory: ./server 

      - name: Build project
        run:  npm run build:all
        working-directory: ./server  

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./server/build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v2
      - name: Download Build
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./server/build
      - name: "Create .netrc for Heroku Auth"
        shell: bash
        run: |
          `cat >~/.netrc <<EOF
          machine api.heroku.com
              login $EMAIL
              password $HEROKU_API_KEY
          machine git.heroku.com
              login $EMAIL
              password $HEROKU_API_KEY
          EOF`
        env:
          EMAIL: philippe.depauw@arteveldehs.be
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      - name: "Add remote"
        shell: "bash"
        run: |
          heroku git:remote --app the8gency
      - name: "Push to heroku"
        shell: "bash"
        run: |
          git push heroku HEAD:master
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "the8gency"
          heroku_email: "philippe.depauw@arteveldehs.be"
          buildpack: "nodejs"
          dontuseforce: false
