name: Deploy to Heroku Hosting (Production)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.1
      
      - name: Install NPM packages
        run: npm ci
        working-directory: ./server 

      - name: Build project
        run:  npm run build:all
        working-directory: ./server  

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./server/build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v2
      - name: Download Build
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./server/build
      - name: Move files and directories to root
        shell: bash
        run: |
          mv ./server/build/* ./
          rm -rf ./server
      - name: "Create .netrc for Heroku Auth"
        shell: bash
        run: |
          `cat >~/.netrc <<EOF
          machine api.heroku.com
              login $EMAIL
              password $HEROKU_API_KEY
          machine git.heroku.com
              login $EMAIL
              password $HEROKU_API_KEY
          EOF`
        env:
          EMAIL: ${{ secrets.HEROKU_EMAIL }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      - name: "Add remote"
        shell: "bash"
        run: |
          heroku git:remote --app ${{ secrets.HEROKU_APP_NAME }}
          heroku config:set NODE_MODULES_CACHE=true -app ${{ secrets.HEROKU_APP_NAME }}
      - name: "Push to heroku"
        shell: "bash"
        run: |
          git fetch --prune --unshallow
          git push heroku HEAD:main -f
