name: Deploy to Heroku Hosting (Production)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.1
      
      - name: Install NPM packages
        run: npm ci
        working-directory: ./server 

      - name: Build project
        run:  npm run build:all
        working-directory: ./server  

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./server/build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v2
      - name: Download Build
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./server/build
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          docker_heroku_process_type: web
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "the8gency"
          heroku_email: "philippe.depauw@arteveldehs.be"
          appdir: "server/build"
          procfile: "web:node server/build/app.js"
          justlogin: true
          
      - name: "Login to heroku registry"
        run: heroku container:login

      - name: "Build and push to heroku registry"
        run: heroku container:push web --app the8gency

      - name: "Releases the container"
        run: heroku container:release web --app the8gency
